table _measures
	lineageTag: a729386f-03ba-405b-8a64-0bba25d8e75c

	measure 'Active Sellers' = DISTINCTCOUNT( fact_order_items[seller_id] )
		formatString: 0
		lineageTag: a82ae131-b8a1-4ada-849b-e1edb09a7854

	measure 'Avg Delivery Delay' =
			
			AVERAGEX(
			    FILTER(
			        dim_orders,
			        dim_orders[order_delivered_customer_date] >
			        dim_orders[order_estimated_delivery_date]
			    ),
			    dim_orders[order_delivered_customer_date] -
			    dim_orders[order_estimated_delivery_date]
			)
		lineageTag: 51c17256-2bfd-4d55-9fca-b0df15c0d705

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Seller Review' =
			
			CALCULATE(
			    AVERAGE( 'dim_order_reviews'[review_score] )
			)
		lineageTag: 8b1c675a-b213-4f55-8097-4f6d0c6eeb80

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Late Delivery Rate' =
			
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(dim_orders),
			        dim_orders[Delivery_Status] = "Late"
			    ),
			    COUNTROWS(dim_orders)
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: af08afa2-fea8-4fc5-867f-91df832fd8d9

	measure 'Total Sales by Category' = SUM(fact_order_items[price])
		lineageTag: 9c66a638-7fcf-4725-ba09-78620cd600ac

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders' =
			
			DISTINCTCOUNT(fact_order_items[order_id])
		formatString: 0
		lineageTag: dfb531e5-e69a-4184-9586-b29d95c02a8e

	measure 'Total Items Sold' = COUNTROWS(fact_order_items)
		formatString: #,0
		lineageTag: 6cae43dc-1bba-411f-8be0-648a41d2438d

	measure 'Average Order Value' =
			
			DIVIDE(
			    SUM(fact_order_items[price]),
			    [Total Orders]
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: be5d369f-820b-4b29-a6be-94a241838429

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Cancellation Rate' =
			
			DIVIDE (
			    CALCULATE (
			        COUNTROWS ( 'dim_orders' ),
			        'dim_orders'[order_status] = "canceled"
			    ),
			    COUNTROWS ( 'dim_orders' )
			)
		formatString: 0%;-0%;0%
		lineageTag: 7d23dc0f-ca03-4201-a489-e60821b295b0

	measure 'Total Customers' =
			
			VAR CustomersWithOrders =
			    ADDCOLUMNS (
			        VALUES ( dim_orders[customer_id] ),
			        "OrderCount", CALCULATE ( COUNTROWS ( dim_orders) )
			    )
			RETURN
			COUNTROWS ( CustomersWithOrders )
		formatString: 0
		lineageTag: ef9555f3-e761-467a-a91a-46b1804b6acd

	measure 'Repeat Customers' = ```
			
			VAR CustomersWithOrders =
			    ADDCOLUMNS (
			        VALUES ( dim_orders[customer_id] ),
			        "OrderCount", CALCULATE ( COUNTROWS ( dim_orders ) )
			    )
			RETURN
			COUNTROWS (
			    FILTER ( CustomersWithOrders, [OrderCount] > 1 )
			)
			
			```
		formatString: 0
		lineageTag: 7bc15951-2229-4286-b4e5-73771d99e606

	column Column
		formatString: 0
		lineageTag: 78e481c3-5d6e-4f60-af28-f6b4dceac4a6
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition _measures = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 33520f87af984e549fd7a2120d45aede

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

