table dim_products
	lineageTag: 5e666372-a1a1-459f-a7be-4800c45c6ace

	column product_id
		dataType: string
		lineageTag: 706d13fe-cc0e-4382-8b71-752125d30fdf
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_category_name
		dataType: string
		lineageTag: eaf54f70-c456-4fef-8201-761fe8748f40
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	column product_name_lenght
		dataType: int64
		formatString: 0
		lineageTag: cdb34c54-8817-42e9-87ce-777f421645b5
		summarizeBy: sum
		sourceColumn: product_name_lenght

		annotation SummarizationSetBy = Automatic

	column product_description_lenght
		dataType: int64
		formatString: 0
		lineageTag: 334f41d4-2855-460a-850a-101e7ad07c80
		summarizeBy: sum
		sourceColumn: product_description_lenght

		annotation SummarizationSetBy = Automatic

	column product_photos_qty
		dataType: int64
		formatString: 0
		lineageTag: 97602022-ab1e-4eb5-b73d-11cd771d99b4
		summarizeBy: sum
		sourceColumn: product_photos_qty

		annotation SummarizationSetBy = Automatic

	column product_weight_g
		dataType: int64
		formatString: 0
		lineageTag: 9537cc2a-fcbd-43ab-a5b5-94aa79757a71
		summarizeBy: sum
		sourceColumn: product_weight_g

		annotation SummarizationSetBy = Automatic

	column product_length_cm
		dataType: int64
		formatString: 0
		lineageTag: d01a9036-3535-475c-a16d-5e3d3339bf54
		summarizeBy: sum
		sourceColumn: product_length_cm

		annotation SummarizationSetBy = Automatic

	column product_height_cm
		dataType: int64
		formatString: 0
		lineageTag: 456a3895-167d-4513-8702-bb4e6cb67116
		summarizeBy: sum
		sourceColumn: product_height_cm

		annotation SummarizationSetBy = Automatic

	column product_width_cm
		dataType: int64
		formatString: 0
		lineageTag: 3a4c0518-5fbd-4507-8ded-ade53b914138
		summarizeBy: sum
		sourceColumn: product_width_cm

		annotation SummarizationSetBy = Automatic

	partition dim_products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Melissa\Documents\Personal Portfolio Projects\Power BI\Olist\olist datacsv\olist_products_dataset.csv"),[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"product_id", type text}, {"product_category_name", type text}, {"product_name_lenght", Int64.Type}, {"product_description_lenght", Int64.Type}, {"product_photos_qty", Int64.Type}, {"product_weight_g", Int64.Type}, {"product_length_cm", Int64.Type}, {"product_height_cm", Int64.Type}, {"product_width_cm", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

